In [1]:
import sys
sys.path.append('../src')
import numpy as np
import pandas as pd
# from statsmodels.tsa.ar_model import AutoReg
import tensorflow as tf

## Model Description

The `input_shape` argument specifies (`time_steps`, `n_features`)

## Data Processing

In [2]:
# Get one timeseries of fuel moisture data
df = pd.read_pickle("../data/rocky_2023_05-09.pkl")
# First STID from unique
st = df.stid.unique()[0]
fm = df.fm[df.stid == st].to_numpy()
print(f"Station: {st}")
print(f"N observations: {len(fm)}")

Station: CPTC2
N observations: 3627


In [3]:
# ar = AutoReg(fm, lags=1).fit()

In [4]:
# ar.summary()

## RNN

In [5]:
# # Prepare data for RNN
X = fm[:-1]  # Input sequence
y = fm[1:]   # Output sequence (shifted by 1 time step)

# # Define RNN parameters
input_dim = X.shape[-1]   # Number of features
output_dim = y.shape[-1]  # Number of features
# hidden_units = 1          # Number of units in the RNN layer
# num_steps = X.shape[0]     # Number of time steps
# batch_size = 1             # Batch size for training

In [6]:
output_dim

3626

In [15]:
model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units = 1, input_shape=(input_dim, 1), activation="linear"),
    tf.keras.layers.Dense(units=1, activation="linear")
])
model.compile(loss='mean_squared_error', optimizer='adam')

In [16]:
wx = model.get_weights()[0]
wh = model.get_weights()[1]
bh = model.get_weights()[2]
wy = model.get_weights()[3]
by = model.get_weights()[4]
 
print('wx = ', wx, ' wh = ', wh, ' bh = ', bh, ' wy =', wy, 'by = ', by)

wx =  [[1.5359861]]  wh =  [[1.]]  bh =  [0.]  wy = [[1.433561]] by =  [0.]


In [17]:
model.get_weights()

[array([[1.5359861]], dtype=float32),
 array([[1.]], dtype=float32),
 array([0.], dtype=float32),
 array([[1.433561]], dtype=float32),
 array([0.], dtype=float32)]

## References

https://machinelearningmastery.com/understanding-simple-recurrent-neural-networks-in-keras/